name: Laravel Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      # Use a service container for the database (e.g., MySQL or Postgres)
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: --health-cmd="mysqladmin ping"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        # This action sets up PHP, required extensions, and automatically handles Composer caching.
        uses: shivammathur/setup-php@v2
        with:
          # Note: PHP 8.4 may not be stable in all CI environments yet. Use a stable version like '8.3' if issues arise.
          php-version: '8.4' 
          extensions: mbstring, pdo, mysql, bcmath, ctype, fileinfo, json, tokenizer, xml, openssl, curl, zip
          tools: composer:v2

      - name: Copy .env
        run: cp .env.example .env

      - name: Update DB configuration for testing
        run: |
          sed -i '/^DB_CONNECTION=/c\DB_CONNECTION=mysql' .env
          sed -i '/^DB_HOST=/c\DB_HOST=127.0.0.1' .env
          sed -i '/^DB_PORT=/c\DB_PORT=3306' .env
          sed -i '/^DB_DATABASE=/c\DB_DATABASE=test_db' .env
          sed -i '/^DB_USERNAME=/c\DB_USERNAME=root' .env
          sed -i '/^DB_PASSWORD=/c\DB_PASSWORD=root' .env
        
      - name: Install Composer Dependencies
        run: composer install --prefer-dist --no-ansi --no-interaction --no-progress

      - name: Generate key
        run: php artisan key:generate

      # --- Frontend Build Steps (Added for npm run build) ---

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a modern LTS version

      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Node Dependencies
        # Only runs if node_modules cache misses
        run: npm install

      - name: Run Frontend Build
        # Compiles assets necessary for some features/tests (e.g., Blade components)
        run: npm run build

      # --- End Frontend Build Steps ---

      - name: Run Migrations
        # The 'artisan migrate' command should run migrations on the test database
        run: php artisan migrate --force

      - name: Execute tests (PHPUnit/Pest)
        # Use your configured test runner command
        run: vendor/bin/phpunit
        # Alternatively, for Pest: run: vendor/bin/pest